### ISSUE TITLE
Issue with Arrival Time Order

### ISSUE THREAD

**Issue by ranjim** [aryanxxvii/process-scheduling#2]
I went through the code in `fcfs.js` and suspect one issue. The function takes in arrival times as input for respective Jobs but it assumes that the `Jobs {Job 1, Job 2, Job 3}` have arrival times in increasing order of time. But what if `Job 1` arrives after `Job 2`.

If it is explicitly mentioned that Jobs are numbered in *increasing order* of arrival times, then it should not be a problem, otherwise I think a check should be there.

**Comment by aryanxxvii** [comment]
Added a sort function before scheduling 👍
